#!/bin/sh

# Copyright:   (c) 2022, Vladimir Vons, UA
# Author:      Vladimir Vons <VladVons@gmail.com>
# Created:     2022.02.16
# License:     GNU, see LICENSE for more details
# Description:

# Exit on error
set -e

#. /usr/share/debconf/confmodule
Name="vhttp-slow-pages"


Configure()
{
    ##pip3 install aiohttp-socks 2>&1

    if which py3compile >/dev/null 2>&1; then
        py3compile -p $Name
    fi

    LogDir=/var/log/$Name
    mkdir -p $LogDir

    touch $LogDir/$Name.log
    chmod 640 $LogDir/$Name.log

    if [ -x "/etc/init.d/$Name" ]; then
        update-rc.d $Name defaults
        update-rc.d $Name enable
    fi
}

case "$1" in
  configure)
    Configure
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

exit 0
