#!/bin/sh

# Exit on error
set -e

#. /usr/share/debconf/confmodule
Name="vhttp-slow-pages"


if which py3clean >/dev/null 2>&1; then
    py3clean -p $Name
fi

if [ "$1" = "purge" ] ; then
    update-rc.d $Name remove >/dev/null
fi

if [ -d /run/systemd/system ] ; then
    systemctl --system daemon-reload >/dev/null || true
fi

#echo "postrm: $1" >> /$Name.log
